### ISSUE TITLE
ClassNotFoundException in WebStorm 9

### ISSUE THREAD

**Issue by victor-homyakov** [dkandalov/code-history-mining#18]
Latest available in repository version (0.2.3 beta) does not work in WebStorm 9.

```
2015-02-02 13:03:33,770 [      0]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE STARTED ------------------------------------------------------ 
2015-02-02 13:03:33,802 [     32]   INFO -        #com.intellij.idea.Main - IDE: WebStorm (build #WS-139.1112, 19 Jan 2015 00:00) 
2015-02-02 13:03:33,802 [     32]   INFO -        #com.intellij.idea.Main - OS: Windows 7 (6.1, amd64) 
2015-02-02 13:03:33,802 [     32]   INFO -        #com.intellij.idea.Main - JRE: 1.8.0_31-b13 (Oracle Corporation) 
2015-02-02 13:03:33,802 [     32]   INFO -        #com.intellij.idea.Main - JVM: 25.31-b07 (Java HotSpot(TM) 64-Bit Server VM) 
2015-02-02 13:03:33,804 [     34]   INFO -        #com.intellij.idea.Main - JVM Args: -Xms128m -Xmx750m -XX:MaxPermSize=350m -XX:ReservedCodeCacheSize=225m -ea -Dsun.io.useCanonCaches=false -Djava.net.preferIPv4Stack=true -Djsse.enableSNIExtension=false -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -Xbootclasspath/a:C:\Program Files (x86)\JetBrains\WebStorm 9.0\lib\boot.jar -Didea.platform.prefix=WebStorm -Didea.no.jre.check=true -Didea.paths.selector=WebStorm9 
2015-02-02 13:03:33,912 [    142]   INFO -        #com.intellij.idea.Main - JNA library loaded (64-bit) in 108 ms 
2015-02-02 13:03:33,914 [    144]   INFO - penapi.util.io.win32.IdeaWin32 - Native filesystem for Windows is operational 
2015-02-02 13:03:33,915 [    145]   INFO -        #com.intellij.idea.Main - Using "FocusKiller" library to prevent focus stealing. 
2015-02-02 13:03:34,936 [   1166]   INFO - llij.ide.plugins.PluginManager - 69 plugins initialized in 566 ms 
2015-02-02 13:03:34,945 [   1175]   INFO - llij.ide.plugins.PluginManager - Loaded bundled plugins: ASP (0.1), AngularJS (139.1112), CSS Support, CoffeeScript (2.0), Dart (139.1112), EJS (139.1112), EditorConfig (1.0), File Watchers (139.1112), Git Integration (8.1), GitHub, HAML, HTML Tools (2.0), Handlebars/Mustache (139.1112), IDEA CORE, IntelliLang (8.0), JSTestDriver Plugin (139.1112), Jade (139.1112), Java Server Pages Integration (1.0), JavaScript Debugger (1.0), JavaScript Intention Power Pack (0.9.4), JavaScript Support (1.0), Karma (139.1112), LESS support, LiveEdit (999.0), Meteor (139.1112), NodeJS (139.1112), PhoneGap/Cordova Plugin (139.1112), Polymer & Web Components (139.1112), QuirksMode, REST Client, Refactor-X (2.01), Remote Hosts Access (0.1), SASS support, Spy-js (139.1112), Stylus support (139.1112), Task Management (1.0), Terminal (0.1), W3C Validators (2.0), XPathView + XSLT Support (4), YAML 
2015-02-02 13:03:34,945 [   1175]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: .gitignore .hgignore .npmignore .dockerignore support (0.8), BashSupport (1.3.3), CMD Support (1.0.4), Code History Mining (0.2.3 beta), CodeGlance (1.4.2), Css Alphabetical Rearranger (0.4), Dummy Text Generator (1.0.11), Ini4Idea (139.732), Key promoter (1.0.11), Lua (1.0.79-139), Markdown (0.9.7), Navigate From Literal (1.8), RegexpTester (1.0.5), Require.js plugin (0.21), String Manipulation (2.9.135.445), SvgViewer 2 (2.0.3), Tasks Navigation (0.3.4), Unicode Browser (0.7.0-10.5), Zero Width Characters locator (0.9) 
2015-02-02 13:03:34,945 [   1175]   INFO - llij.ide.plugins.PluginManager - Disabled plugins: CVS Integration (11), CommonJS AutoComplete (0.1.0), Cucumber.js (139.1112), Gherkin (999.999), Git Flow Integration (0.4), Perforce Integration (2.0), Subversion Integration (1.1), TextMate bundles support (VERSION), XSLT-Debugger (1.4), hg4idea (10.0) 
2015-02-02 13:03:35,229 [   1459]   INFO - ellij.util.io.PagedFileStorage - lower=100; upper=200; buffer=10; max=739246080 
2015-02-02 13:03:35,278 [   1508]   INFO - api.vfs.impl.local.FileWatcher - Starting file watcher: C:\Program Files (x86)\JetBrains\WebStorm 9.0\bin\fsnotifier.exe 
2015-02-02 13:03:35,287 [   1517]   INFO - api.vfs.impl.local.FileWatcher - Native file watcher is operational. 
2015-02-02 13:03:35,379 [   1609]   INFO - pi.util.registry.RegistryState - Registry values changed by user: 
2015-02-02 13:03:35,379 [   1609]   INFO - pi.util.registry.RegistryState -   ide.mac.message.dialogs.as.sheets = true 
2015-02-02 13:03:35,736 [   1966]   INFO - lij.diagnostic.DebugLogManager - Set DEBUG for the following categories: [] 
2015-02-02 13:03:36,433 [   2663]   INFO - lij.util.xmlb.OptionTagBinding - Duplicate options for org.jetbrains.contest.keypromoter.KeyPromoterSettings@c5e64e03 will be ignored 
2015-02-02 13:03:36,724 [   2954]  ERROR -              CodeHistoryMining - Error during initialization 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at codemining.AppComponent.initComponent(AppComponent.java:39)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:567)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:609)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:236)
	at com.intellij.util.pico.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:223)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:210)
	at org.picocontainer.alternatives.AbstractDelegatingMutablePicoContainer.getComponentInstance(AbstractDelegatingMutablePicoContainer.java:75)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:124)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:358)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:115)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:86)
	at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:110)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:493)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:158)
	at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:66)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:364)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NoClassDefFoundError: com/intellij/openapi/compiler/CompilationStatusAdapter
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
	at java.lang.Class.getDeclaredMethods(Class.java:1967)
	at org.codehaus.groovy.reflection.CachedClass$3$1.run(CachedClass.java:84)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.codehaus.groovy.reflection.CachedClass$3.initValue(CachedClass.java:81)
	at org.codehaus.groovy.reflection.CachedClass$3.initValue(CachedClass.java:79)
	at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:46)
	at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:33)
	at org.codehaus.groovy.reflection.CachedClass.getMethods(CachedClass.java:250)
	at groovy.lang.MetaClassImpl.populateMethods(MetaClassImpl.java:342)
	at groovy.lang.MetaClassImpl.fillMethodIndex(MetaClassImpl.java:292)
	at groovy.lang.MetaClassImpl.initialize(MetaClassImpl.java:3045)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:176)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:192)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.getMetaClass(MetaClassRegistryImpl.java:255)
	at org.codehaus.groovy.runtime.InvokerHelper.getMetaClass(InvokerHelper.java:859)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:72)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:159)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at codemining.plugin.ui.UI.grabHistory(UI.groovy:111)
	at codemining.plugin.ui.UI.init(UI.groovy:31)
	at codemining.plugin.ui.UI$init.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at plugin.run(plugin.groovy:28)
	... 35 more
Caused by: java.lang.ClassNotFoundException: com.intellij.openapi.compiler.CompilationStatusAdapter PluginClassLoader[CodeHistoryMining, 0.2.3 beta]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 63 more
2015-02-02 13:03:36,727 [   2957]  ERROR -              CodeHistoryMining - WebStorm 9.0.3  Build #WS-139.1112 
2015-02-02 13:03:36,727 [   2957]  ERROR -              CodeHistoryMining - JDK: 1.8.0_31 
2015-02-02 13:03:36,727 [   2957]  ERROR -              CodeHistoryMining - VM: Java HotSpot(TM) 64-Bit Server VM 
2015-02-02 13:03:36,728 [   2958]  ERROR -              CodeHistoryMining - Vendor: Oracle Corporation 
2015-02-02 13:03:36,728 [   2958]  ERROR -              CodeHistoryMining - OS: Windows 7 
```

**Comment by dkandalov** [comment]
Thanks a lot for reporting this, I uploaded new version (0.2.4 beta) which doesn't have dependency on this class and should work.

**Comment by victor-homyakov** [comment]
Now it works fine. Thanks!
